### ISSUE TITLE
Serial Port Read Failures

### ISSUE THREAD

**Issue by NCharabaruk** [tonybaltovski/ros_arduino#10]
Hey Tony,

I get a lot of serial port read failures while using the IMU. The number of bytes recieved varies, but below you can see what I mean. Usually I get several in a row. Any ideas?

[WARN] [WallTime: 1436540980.150618] Serial Port read failure: 
[WARN] [WallTime: 1436540983.389940] Serial Port read returned short (expected 99 bytes, received 84 instead).

[WARN] [WallTime: 1436541459.907242] Serial Port read failure: 
[WARN] [WallTime: 1436541471.306349] Serial Port read returned short (expected 99 bytes, received 38 instead).

**Comment by tonybaltovski** [comment]
You trying to publishing to quickly for your given case.  Decreasing the publishing rate or increasing the buffer (for exampple `ros::NodeHandle_<ArduinoHardware, 1, 1, 1024, 1024> nh;`)  should fix the issue.

**Comment by NCharabaruk** [comment]
Lowering the refresh rate did it, thanks.

**Comment by miguel7676** [comment]
How do you lower the refresh rate? I am currently using an arduino leonardo and this error is keeping me back a lot. If i increase the buffer size it seems to give problems with the board?

**Comment by NCharabaruk** [comment]
In ros_raw_imu.ino there is a variable update_frequency. Lower it.

**Comment by miguel7676** [comment]
Thank you very much for the reply. Sorry the question might have seemed silly but im not actually using this package (so didnt have the update_freq parameter), just came across the same error and hoped to find a solution. Is it essentially the rate at which published ? Or could this error arise from various things?

**Comment by mikehosmar** [comment]
The Arduino has limited memory.  A large chunk of it is set aside for transmit and receive buffers.  These buffers will fill up and drop parts of your messages if you publish too quickly especially when using message types with many large allocated variables ie doubles or arrays.

**Comment by miguel7676** [comment]
I am currently publishing three range_msgs (sensor_msgs/Range) as well as two encoders which are Float 32. If I add a delay at the end of the loop is this essentially slowing down the publishing? If I add a second delay should I stlll be receiving the serial Port read failure? Is this perhaps another problem?

**Comment by bobness64** [comment]
I had this problem and found GORT which is a serial monitor program was the error.
Just having GORT installed caused the connection to behave erratically so you have to completely uninstall gort and restart the computer

**Comment by Zippen-Huang** [comment]
I changed that   typedef NodeHandle_<ArduinoHardware, 5, 5, 1024, 1024> NodeHandle; in ros.h of rosserial package.
then I comed across the problem:Serial Port read returned short (expected 99 bytes, received 38 instead).
How can I solve it？

**Comment by bobness64** [comment]
There are a few things that cause this issue. They are mainly related to data speed of your connection and how cluttered the USB connection gets.

You should verify you aren't running any other program on your serial port that is why I had issues with GORT as it was taking up all the bandwidth on the serial connection. Also if you are trying to power something more than just a board or are using a wireless connection this error can also appear. For example I still get this error when my bluetooth vehicle goes to far away from the transmitter as data packets get lost in transmission.

How many things are you trying to publish and subscribe and what is the data types? are you publishing arrays or just ints or bytes.
And I take it you know the command NodeHandle_<ArduinoHardware, 5, 5, 1024, 1024> NodeHandle; is setting up 5 subscribers and 5 publishers each with 1024 bytes. Meaning if you have more subscribers or publishers than 5 of either you could be running into buffer flow.

If this doesn't fix your problem an explanation of what you are trying to achieve, data types, commands, hardware etc will help the community in diagnosing the problem.

**Comment by Zippen-Huang** [comment]
A new problem:I want to use telekeyboard send twist message to arduino due,and then the motor can not rotate,it is confusing,I don not know why?
Then I try next steps:first,I just use arduino IDE,set linear = 0.5(m/s),and upload my code,then motor can rotate normally;next,I change linear = 0,and upload,and I open terminal ,running roscore,and run"rosrun rosserial_python rosserial_node.py /dev/ttyACM0",and then ,come out :connect to /dev/ttyACM0 baudrate 57600,sometimes may show :,and then rosrun teleop_twist_keyboard 
teleop_twist_keyboard.py,type "i",motor can not rotate ,then I use arduino publish PWM value,arduio recieved twist message from ros by keyboard,and it is same as value that are from Serial.print() function.(when I use Serial class,I do not use rosserial_arduino).That is mean to I use ros send twist message,motor can not work,but only use arduino due IDE,set the linear value directly,motor can work,it is amazing that I do have no idiea to solve,the ptoblem has stayed for 2 days.

And for the problem "sync......." ,I just copy roslib from my classmate, and then it disappeared.but come across the new problem.I also do not know why.

for " NodeHandle_<ArduinoHardware, 5, 5, 1024, 1024> NodeHandle",I changed it in node_handle.h,it works.
Thank you for very much.

**Comment by AIHZP** [comment]
A new problem:I want to use telekeyboard send twist message to arduino due,and then the motor can not rotate,it is confusing,I don not know why?
Then I try next steps:first,I just use arduino IDE,set linear = 0.5(m/s),and upload my code,then motor can rotate normally;next,I change linear = 0,and upload,and I open terminal ,running roscore,and run"rosrun rosserial_python rosserial_node.py /dev/ttyACM0",and then ,come out :connect to /dev/ttyACM0 baudrate 57600,sometimes may show :,and then rosrun teleop_twist_keyboard 
teleop_twist_keyboard.py,type "i",motor can not rotate ,then I use arduino publish PWM value,arduio recieved twist message from ros by keyboard,and it is same as value that are from Serial.print() function.(when I use Serial class,I do not use rosserial_arduino).That is mean to I use ros send twist message,motor can not work,but only use arduino due IDE,set the linear value directly,motor can work,it is amazing that I do have no idiea to solve,the ptoblem has stayed for 2 days.

And for the problem "sync......." ,I just copy roslib from my classmate, and then it disappeared.but come across the new problem.I also do not know why.

for " NodeHandle_<ArduinoHardware, 5, 5, 1024, 1024> NodeHandle",I changed it in node_handle.h,it works.
Thank you for very much.
