### ISSUE TITLE
Trouble including libraries

### ISSUE THREAD

**Issue by Pandaii** [tonybaltovski/ros_arduino#8]
Hello!
I have trouble compiling the two_wheel_base.ino file. It includes encoder.h then ros/serialization but then it tries to include boost/shared_array.hpp. But it seems that arduino doesn't recognize .hpp files.

My encoder.h file starts like this:

<pre>
#include string
#include vector
#include map

#include ros/types.h
#include ros/serialization.h
#include ros/builtin_message_traits.h
#include ros/message_operations.h

#include std_msgs/Header.h
</pre>

I have no idea how to enable arduino to include all the files it requests...

Thanks

**Comment by tonybaltovski** [comment]
To generate the headers for an Arduino, use `install_ros_lib.sh` which runs `rosrun rosserial_arduino make_libraries.py .` to generate the headers into the correct folder.

**Comment by tonybaltovski** [comment]
@Pandaii any updates?

**Comment by Pandaii** [comment]
Thanks, it compiles fine now. ^^
